### ISSUE TITLE
每行最后一个字指针和文字重叠了

### ISSUE THREAD

**Issue by shaochangxing** [Z-Siqi/WritingBoard#1]
![823c9e8d9931f40b4b0121685062425](https://github.com/Z-Siqi/WritingBoard/assets/11647361/8d75afae-4187-41a6-8209-3fd2e4652314)

**Comment by Z-Siqi** [comment]
有没有试过beta的？
https://github.com/Z-Siqi/WritingBoard/raw/master/app/release/app-release.apk

**Comment by shaochangxing** [comment]
用的就是beta的，大概测了一下，最后一行是没问题的，上面的行只有最后一个字有这种问题。不过也不妨碍用，就是有点别捏。

**Comment by Z-Siqi** [comment]
这个问题无法在我的设备上复现，能否告诉我你的设备，Android版本信息？这可能有助于修复

**Comment by shaochangxing** [comment]
![27399c6c11562be3b2ac0e961b5b96d](https://github.com/Z-Siqi/WritingBoard/assets/11647361/ca5d7c68-40d8-46f5-ba91-5c4ec35fe78a)

![f71647cedb393e89b85d3f58e813b5a](https://github.com/Z-Siqi/WritingBoard/assets/11647361/4702902b-df4b-433c-ad8b-572bf7cf4620)

**Comment by Z-Siqi** [comment]
是否可以再提供一下引发错误的录屏？

**Comment by shaochangxing** [comment]
你好问题解决了，是系统字体的问题，是我使用了第三方的字体导致的，使用默认字体就没问题了。
