### ISSUE TITLE
更新到最新版后，笔记的内容总是会复制一份拼接到最后面。

### ISSUE THREAD

**Issue by shaochangxing** [Z-Siqi/WritingBoard#2]
大概就是比如我打开app看了一下内容，然后切换到后台，过了一阵之后再次打开就会出现原来的笔记内容复制一份拼接到后面。但是我直接测试切换后台又测不出来这个问题。

**Comment by Z-Siqi** [comment]
尝试升级到 beta 版再试试

https://github.com/Z-Siqi/WritingBoard/raw/master/app/release/app-release.apk

**Comment by Z-Siqi** [comment]
如果问题在 0.5.8 之后仍然存在，请再次反馈
